# Generated by Django 4.2.7 on 2025-08-25 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='answer',
            name='psy_toolkit_data',
            field=models.JSONField(default=dict, verbose_name='Данные PsyToolkit'),
        ),
        migrations.AddField(
            model_name='question',
            name='psy_toolkit_data',
            field=models.JSONField(default=dict, verbose_name='Данные PsyToolkit'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='multiple_choice', max_length=50, verbose_name='Тип вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Обязательный'),
        ),
        migrations.AddField(
            model_name='test',
            name='difficulty_level',
            field=models.CharField(default='medium', max_length=20, verbose_name='Уровень сложности'),
        ),
        migrations.AddField(
            model_name='test',
            name='estimated_duration',
            field=models.IntegerField(default=10, verbose_name='Примерная длительность (мин)'),
        ),
        migrations.AddField(
            model_name='test',
            name='psy_toolkit_data',
            field=models.JSONField(default=dict, verbose_name='Данные PsyToolkit'),
        ),
        migrations.AddField(
            model_name='test',
            name='psy_toolkit_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID в PsyToolkit'),
        ),
        migrations.AddField(
            model_name='test',
            name='source',
            field=models.CharField(default='custom', max_length=50, verbose_name='Источник теста'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(default='personality', max_length=50, verbose_name='Тип теста'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='psy_toolkit_raw_data',
            field=models.JSONField(default=dict, verbose_name='Сырые данные PsyToolkit'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='psy_toolkit_result_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID результата в PsyToolkit'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='completed_psy_toolkit_tests',
            field=models.JSONField(default=list, verbose_name='Завершенные PsyToolkit тесты'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='psy_toolkit_preferences',
            field=models.JSONField(default=dict, verbose_name='Предпочтения PsyToolkit'),
        ),
        migrations.CreateModel(
            name='PsyToolkitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название теста')),
                ('description', models.TextField(verbose_name='Описание')),
                ('psy_toolkit_id', models.CharField(max_length=100, unique=True, verbose_name='ID в PsyToolkit')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('tags', models.JSONField(default=list, verbose_name='Теги')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Сырые данные PsyToolkit')),
                ('is_imported', models.BooleanField(default=False, verbose_name='Импортирован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.test', verbose_name='Импортированный тест')),
            ],
            options={
                'verbose_name': 'PsyToolkit тест',
                'verbose_name_plural': 'PsyToolkit тесты',
            },
        ),
        migrations.CreateModel(
            name='PsyToolkitImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='Статус')),
                ('details', models.JSONField(default=dict, verbose_name='Детали импорта')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Импортировал')),
                ('imported_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test', verbose_name='Импортированный тест')),
                ('psy_toolkit_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.psytoolkittest', verbose_name='PsyToolkit тест')),
            ],
            options={
                'verbose_name': 'Лог импорта PsyToolkit',
                'verbose_name_plural': 'Логи импорта PsyToolkit',
            },
        ),
    ]
