# Generated by Django 4.2.7 on 2025-08-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_answer_is_correct_answer_psy_toolkit_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='psy_toolkit_data',
        ),
        migrations.AddField(
            model_name='question',
            name='confidence_required',
            field=models.BooleanField(default=False, verbose_name='Уверенность обязательна'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание изображения'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения'),
        ),
        migrations.AddField(
            model_name='question',
            name='show_confidence_scale',
            field=models.BooleanField(default=True, verbose_name='Показывать шкалу уверенности'),
        ),
        migrations.AddField(
            model_name='test',
            name='adaptive_scoring',
            field=models.BooleanField(default=False, verbose_name='Адаптивная система баллов'),
        ),
        migrations.AddField(
            model_name='test',
            name='confidence_weight',
            field=models.FloatField(default=1.0, verbose_name='Вес уверенности в результатах'),
        ),
        migrations.AddField(
            model_name='test',
            name='image_required',
            field=models.BooleanField(default=False, verbose_name='Изображения обязательны'),
        ),
        migrations.AddField(
            model_name='test',
            name='show_confidence_scale',
            field=models.BooleanField(default=True, verbose_name='Показывать шкалу уверенности'),
        ),
        migrations.AddField(
            model_name='test',
            name='show_images',
            field=models.BooleanField(default=False, verbose_name='Показывать изображения'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='test',
            name='estimated_duration',
            field=models.IntegerField(default=15, verbose_name='Примерная длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник'),
        ),
    ]
