# Generated by Django 4.2.7 on 2025-08-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_test_options_remove_test_psy_toolkit_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='confidence_required',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='show_confidence_scale',
        ),
        migrations.RemoveField(
            model_name='test',
            name='adaptive_scoring',
        ),
        migrations.RemoveField(
            model_name='test',
            name='confidence_weight',
        ),
        migrations.RemoveField(
            model_name='test',
            name='image_required',
        ),
        migrations.RemoveField(
            model_name='test',
            name='show_confidence_scale',
        ),
        migrations.RemoveField(
            model_name='test',
            name='show_images',
        ),
        migrations.AddField(
            model_name='test',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения теста'),
        ),
    ]
