# Generated by Django 4.2.7 on 2025-08-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_question_confidence_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание изображения'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения вопроса'),
        ),
    ]
