name: 🚀 Fast Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: 📦 Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: 🔧 Install Python dependencies
      run: |
        cd backend
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 🗄️ Setup Database
      run: |
        cd backend
        python manage.py migrate --noinput
        
    - name: 📁 Collect static files
      run: |
        cd backend
        python manage.py collectstatic --noinput
        
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: 📦 Cache Node modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: 🔧 Install Node dependencies
      run: |
        cd frontend
        npm ci --only=production
        
    - name: 🏗️ Build React app
      run: |
        cd frontend
        npm run build
        
    - name: 🔑 Setup SSH
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p $SERVER_PORT -H $SERVER_HOST >> ~/.ssh/known_hosts
        
    - name: 🚀 Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deploying to production server..."
        
        # Создаем временную папку для деплоя
        mkdir -p deploy-temp
        
        # Копируем только нужные файлы
        cp -r backend deploy-temp/
        cp -r frontend deploy-temp/
        cp -r .github deploy-temp/
        cp docker-compose.yml deploy-temp/ 2>/dev/null || true
        cp nginx.conf deploy-temp/ 2>/dev/null || true
        cp deploy.sh deploy-temp/ 2>/dev/null || true
        cp requirements.txt deploy-temp/ 2>/dev/null || true
        cp package.json deploy-temp/ 2>/dev/null || true
        
        # Создаем архив
        tar -czf psyweb-deploy.tar.gz -C deploy-temp .
        
        # Очищаем временную папку
        rm -rf deploy-temp
        
        # Передаем файлы на сервер
        scp -P $SERVER_PORT psyweb-deploy.tar.gz $SERVER_USER@$SERVER_HOST:/tmp/
        
        # Выполняем деплой на сервере
        ssh -p $SERVER_PORT $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /opt/psyweb || mkdir -p /opt/psyweb && cd /opt/psyweb
          
          # Останавливаем текущие процессы
          pkill -f "python manage.py runserver" || true
          pkill -f "nginx" || true
          
          # Распаковываем новый код
          tar -xzf /tmp/psyweb-deploy.tar.gz -C .
          
          # Устанавливаем зависимости Python
          cd backend
          pip install -r requirements.txt &
          
          # Устанавливаем зависимости Node.js
          cd ../frontend
          npm ci --only=production &
          
          # Ждем завершения установки зависимостей
          wait
          
          # Собираем React приложение
          npm run build &
          
          # Применяем миграции
          cd ../backend
          python manage.py migrate --noinput &
          
          # Собираем статические файлы
          python manage.py collectstatic --noinput &
          
          # Ждем завершения всех операций
          wait
          
          # Запускаем сервисы в фоновом режиме
          python manage.py runserver 0.0.0.0:8000 &
          
          # Запускаем Nginx
          nginx -c /opt/psyweb/nginx.conf &
          
          # Очищаем временные файлы
          rm -f /tmp/psyweb-deploy.tar.gz
          
          echo "✅ Deployment completed on server!"
        EOF
        
    - name: 📊 Deployment success
      if: github.ref == 'refs/heads/main'
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🌐 Application is live at: http://$SERVER_HOST"
        echo "🔗 Server: $SERVER_USER@$SERVER_HOST:$SERVER_PORT"
