name: 🚀 Fast Deploy (Dropbear Compatible)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: 📦 Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: 🔧 Install Python dependencies
      run: |
        cd backend
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 🗄️ Setup Database
      run: |
        cd backend
        python manage.py migrate --noinput
        
    - name: 📁 Collect static files
      run: |
        cd backend
        python manage.py collectstatic --noinput
        
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: 📦 Cache Node modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: 🔧 Install Node dependencies
      run: |
        cd frontend
        npm ci --only=production
        
    - name: 🏗️ Build React app
      run: |
        cd frontend
        npm run build
        
    - name: 🔑 Setup SSH (Dropbear Compatible)
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p ~/.ssh
        
        # Установка sshpass для парольной аутентификации
        sudo apt-get update
        sudo apt-get install -y sshpass
        
        # Настройка SSH config для Dropbear
        echo "Host $SERVER_HOST" >> ~/.ssh/config
        echo "  Port $SERVER_PORT" >> ~/.ssh/config
        echo "  User $SERVER_USER" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
        echo "  ServerAliveInterval 5" >> ~/.ssh/config
        echo "  ServerAliveCountMax 3" >> ~/.ssh/config
        
        # Если есть приватный ключ, используем его
        if [ -n "$SSH_PRIVATE_KEY" ]; then
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "  PubkeyAuthentication yes" >> ~/.ssh/config
          echo "  PasswordAuthentication no" >> ~/.ssh/config
          echo "  PreferredAuthentications publickey" >> ~/.ssh/config
        else
          # Иначе используем пароль
          echo "  PubkeyAuthentication no" >> ~/.ssh/config
          echo "  PasswordAuthentication yes" >> ~/.ssh/config
          echo "  PreferredAuthentications password" >> ~/.ssh/config
        fi
        
        # Тест подключения
        echo "Testing SSH connection to Dropbear server..."
        if [ -n "$SSH_PRIVATE_KEY" ]; then
          ssh -o ConnectTimeout=15 $SERVER_HOST "echo 'SSH connection successful'"
        else
          sshpass -p "$SERVER_PASSWORD" ssh -o ConnectTimeout=15 $SERVER_HOST "echo 'SSH connection successful'"
        fi
        
    - name: 🚀 Deploy to production
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deploying to production server..."
        echo "Server: $SERVER_USER@$SERVER_HOST:$SERVER_PORT"
        
        # Создаем временную папку для деплоя
        mkdir -p deploy-temp
        
        # Копируем только нужные файлы
        cp -r backend deploy-temp/
        cp -r frontend deploy-temp/
        cp -r .github deploy-temp/
        cp docker-compose.yml deploy-temp/ 2>/dev/null || true
        cp nginx.conf deploy-temp/ 2>/dev/null || true
        cp deploy.sh deploy-temp/ 2>/dev/null || true
        cp requirements.txt deploy-temp/ 2>/dev/null || true
        cp package.json deploy-temp/ 2>/dev/null || true
        
        # Создаем архив
        tar -czf psyweb-deploy.tar.gz -C deploy-temp .
        
        # Очищаем временную папку
        rm -rf deploy-temp
        
        # Передаем файлы на сервер
        echo "📤 Uploading files to server..."
        if [ -n "$SSH_PRIVATE_KEY" ]; then
          scp -o ConnectTimeout=30 psyweb-deploy.tar.gz $SERVER_HOST:/tmp/
        else
          sshpass -p "$SERVER_PASSWORD" scp -o ConnectTimeout=30 psyweb-deploy.tar.gz $SERVER_HOST:/tmp/
        fi
        
        # Выполняем деплой на сервере
        echo "🔧 Deploying on server..."
        if [ -n "$SSH_PRIVATE_KEY" ]; then
          ssh -o ConnectTimeout=30 $SERVER_HOST << 'EOF'
        else
          sshpass -p "$SERVER_PASSWORD" ssh -o ConnectTimeout=30 $SERVER_HOST << 'EOF'
        fi
          echo "Starting deployment on server..."
          cd /opt/psyweb || mkdir -p /opt/psyweb && cd /opt/psyweb
          
          # Останавливаем текущие процессы
          echo "Stopping current processes..."
          pkill -f "python manage.py runserver" || true
          pkill -f "nginx" || true
          
          # Распаковываем новый код
          echo "Extracting new code..."
          tar -xzf /tmp/psyweb-deploy.tar.gz -C .
          
          # Устанавливаем зависимости Python
          echo "Installing Python dependencies..."
          cd backend
          pip install -r requirements.txt &
          
          # Устанавливаем зависимости Node.js
          echo "Installing Node.js dependencies..."
          cd ../frontend
          npm ci --only=production &
          
          # Ждем завершения установки зависимостей
          wait
          
          # Собираем React приложение
          echo "Building React app..."
          npm run build &
          
          # Применяем миграции
          echo "Running migrations..."
          cd ../backend
          python manage.py migrate --noinput &
          
          # Собираем статические файлы
          echo "Collecting static files..."
          python manage.py collectstatic --noinput &
          
          # Ждем завершения всех операций
          wait
          
          # Запускаем сервисы в фоновом режиме
          echo "Starting services..."
          python manage.py runserver 0.0.0.0:8000 &
          
          # Запускаем Nginx
          nginx -c /opt/psyweb/nginx.conf &
          
          # Очищаем временные файлы
          rm -f /tmp/psyweb-deploy.tar.gz
          
          echo "✅ Deployment completed on server!"
        EOF
        
    - name: 📊 Deployment success
      if: github.ref == 'refs/heads/main'
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🌐 Application is live at: http://$SERVER_HOST"
        echo "🔗 Server: $SERVER_USER@$SERVER_HOST:$SERVER_PORT"
